server:
  port: 9080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: callback-service
          uri: lb://callback-service
          predicates: Path=/callback/**
        - id: processing-service
          uri: lb://processing-service
          predicates: Path=/processing/**
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        health-check-path: /actuator/health
      host: ${HOST_IP:localhost}
      port: 8500
  main:
    web-application-type: reactive
#zuul:
#  routes:
#    mock-service:
#      path: /mock/**
#      url: http://localhost:9082
#    user-service:
#      path: /demo/**
#      url: http://localhost:9081/temp

logging:
  level:
    org.springframework: INFO
    reactor.icp.netty: INFO
    io.github.demo: DEBUG
