server:
  port: 9081

spring:
  application:
    name: callback-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        health-check-path: /actuator/health
      host: ${HOST_IP:localhost}
      port: 8500
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672